<a href="https://colab.research.google.com/github/Zurezh/Python_LearnByDoing/blob/master/Module_3_Fundamentals_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 3 - Fundamentals of Python

1. Lists
2. Using the [] brackets
3. Slicing
4. Tuples
5. Functions
6. Packages
7. Numpy and Arrays
8. Slicing Arrays

## Lists

In [0]:
myFirstList = [2,3,52,3234,62432]

In [3]:
myFirstList

[2, 3, 52, 3234, 62432]

In [4]:
type(myFirstList)

list

In [0]:
l2 = ['hello',23,True,22.3]

In [6]:
l2

['hello', 23, True, 22.3]

In [0]:
l3 = ['how are you?',55,[3,45,56,234]]

In [8]:
l3

['how are you?', 55, [3, 45, 56, 234]]

---

In [9]:
range(15) #Python 3 - This is the same as xrange() in python 2

range(0, 15)

In [10]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [11]:
x = [1,2,3,4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [0]:
y = list(range(7))

In [13]:
y

[0, 1, 2, 3, 4, 5, 6]

In [0]:
z = list(range(1,9))

In [15]:
z

[1, 2, 3, 4, 5, 6, 7, 8]

In [0]:
z2 = list(range(100,120))

In [17]:
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [0]:
w = list(range(100,210,20))

In [21]:
w

[100, 120, 140, 160, 180, 200]

---

## Using the [] brackets

In [0]:
w = ['a','b','c','d','e']

In [23]:
w

['a', 'b', 'c', 'd', 'e']

In [25]:
w[0]

'a'

In [26]:
len(w)

5

In [27]:
w[4]

'e'

In [28]:
w[-1]

'e'

In [0]:
w[2]=44

In [30]:
w

['a', 'b', 44, 'd', 'e']

## Slicing

In [0]:
letters = ['A','B','C','D','E','F','G','H','I','J']

In [32]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [33]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [34]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [37]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [35]:
letters[2:8]

['C', 'D', 'E', 'F', 'G', 'H']

In [38]:
letters[-8:7]

['C', 'D', 'E', 'F', 'G']

In [39]:
letters[-8:-3]

['C', 'D', 'E', 'F', 'G']

Advanced Slicing

In [36]:
letters[2:9:2]

['C', 'E', 'G', 'I']

In [41]:
letters[::3]

['A', 'D', 'G', 'J']

In [42]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [43]:
letters[7:2:-1]

['H', 'G', 'F', 'E', 'D']

## Tuples

In [0]:
t1 = (234,525,623)

In [45]:
t1

(234, 525, 623)

In [47]:
t1[0]

234

## Functions

In [48]:
range(20,31)

range(20, 31)

In [49]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [0]:
mylist1 = list(range(20,31))

In [51]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [52]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [53]:
len(mylist1)

11

In [54]:
type(mylist1)

list

In [55]:
max(mylist1)

30

In [56]:
min(mylist1)

20

## Packages

A **Module** is simply a file containing Python definitions, functions, and statements. Putting into code into modules is useful because of the ability to import the module functionality into your script or IPython session.

A **Package** is just a way of collecting related modules together within a single tree-like hierarchy. Very complex packages like NumPy of SciPy have hundreds of individual modules so putting them into a directory-like structure keeps things organized and avoids name collisions.

The Steps:
1. Find Package (Optional)
2. Install Package
3. Import Package or Import Function

## Numpy and Arrays in Python

In [0]:
l = [1234,23,22345,22,-234]

In [0]:
import numpy as np

In [0]:
a = np.array(l)

In [60]:
a

array([ 1234,    23, 22345,    22,  -234])

In [0]:
b=np.array([12,455,65.3,True,'a'])

In [62]:
b

array(['12', '455', '65.3', 'True', 'a'], dtype='<U32')

In [63]:
print(b)

['12' '455' '65.3' 'True' 'a']


In [64]:
a.mean()

4678.0

## Slicing Arrays

In [67]:
l[1:]

[23, 22345, 22, -234]

In [68]:
a

array([ 1234,    23, 22345,    22,  -234])

In [69]:
a[2:]

array([22345,    22,  -234])

In [70]:
a[2:4]

array([22345,    22])

In [0]:
b = a[2:4]

In [72]:
b

array([22345,    22])

In [0]:
b[:] = 111

In [74]:
a

array([1234,   23,  111,  111, -234])

In [0]:
c = a.copy()

In [76]:
c

array([1234,   23,  111,  111, -234])